-- Hypr-Deb additions (installer.sh) — kept apart from upstream content.
-- First-run welcome, replacing upstream's autogenerated-config notice.
-- Registered on the hyprland.start event: that is the documented autostart
-- hook (see upstream example/hyprland.lua). A bare top-level hl.exec_cmd
-- fires at config-parse time, before the compositor is up, so the GUI
-- client would have no Wayland display to connect to. The marker lands
-- only when the app exits cleanly (the user closed it), so the welcome
-- keeps appearing until actually acknowledged. Lua long brackets keep the
-- sh quoting sane.
hl.on("hyprland.start", function()
  hl.exec_cmd([[sh -c 'marker="$HOME/.config/hypr/.welcome-shown"; [ -e "$marker" ] || { /usr/local/bin/hyprland-welcome && touch "$marker"; }']])
end)
